os:
  - linux

language: python

env:
  matrix:
  - python=2.7  CONDA_PY=27
  - python=3.5  CONDA_PY=35
  - python=3.6  CONDA_PY=36

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=$python
  - source activate ingeotec  
  - conda install --yes pip
  - pip install coverage
  - pip install coveralls
  - conda config --append channels ingeotec  
  - conda install --yes nose sparsearray
  - python setup.py build_ext --inplace

# command to run tests
script:
  - which python
  - python --version
  - which coverage
  - if [ $python = 2.7 ]; then nosetests --verbose -exe EvoDAG; fi
  - if [ $python = 3.5 ]; then nosetests --verbose -exe EvoDAG; fi
  - if [ $python = 3.6 ]; then coverage run setup.py nosetests; fi

after_success:
  - if [ $python = 3.6 ]; then coveralls || echo "Coveralls upload failed"; fi  
  - if [ $TRAVIS_BRANCH = "master" ]; then source deactivate; conda install --yes pip conda-build jinja2 anaconda-client; conda build conda-recipe --quiet; fi
  - python continuous-integration/move-conda-package.py conda-recipe  
  - which binstar
  - python continuous-integration/binstar-push.py

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
